### ISSUE TITLE
[Bug] Restoring WiFi AP's (Special Backup) results in LOS16 not being able to store&remember WiFi passwords

### ISSUE THREAD

**Issue by CEHitchens** [machiav3lli/oandbackupx#267] opened 2021-01-02 03:27 UTC
**Description**
Having restored the special backup for the WiFi access points, this results in having to re-enter a WiFi network's password after reboots, apparently they don't get stored.
This only ever happened after having used OAndBackupX to restore WiFi AP's.
(for what it's worth: I was able to restore that functionality by restoring WiFi access point _data_ from an earlier TitaniumBackup backup. In there it is referred to as com.keramidas.virtual.WIFI_AP_LIST)

**Steps To Reproduce**

1. Use oandbackupx on LOS16 to backup WiFi access points
2. Restore that WiFi AP backup to the very same device, the very same LOS version (clean install) using oandbackupx
3. Connect to WiFi network, enter password
4. Reboot device
5. Have to enter password for WiFi network again.

**Expected behavior**
The device/OS should remember/store the WiFi network password(s)

**System Information(please complete the following information):**

- Device: SM-T813
- Android Version: 9
- ROM: LineageOS 16.0 (micoG) + Magisk 20.4
- App's Version: OAndBackupX 4.0.0 (from F-Droid)

-----------------------------

**Additional Notes**

* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please report there directly, not here.

* If you're on the latest github version:
  
  * Please read the [FAQ](https://github.com/machiav3lli/oandbackupx/blob/master/FAQ.md) first.
  * Please read all the open Issues. If one does match yours, leave a comment there if there's some extra information you can provide.

* If you're not on the latest github version. Update, then make sure that the bug is still there. If it's go further with reporting.

Thanks for reporting.

**Comment by didierm** [comment] 2021-01-02 10:12
Dupe of issue #252 ?

**Comment by CEHitchens** [comment] 2021-01-02 14:15
> Dupe of issue #252 ?

Possibly, can't rule that out unless if I were to roll back from the roll-back.
I assume that TB set whichever permissions the way they were "before".

BUT I still have the backupped OABX data. I had a look at special.wifi.access.points backup folder, which, in some date/timestamp sub-folder contained a *.tar.gz with ultimately a WifiConfigStore.xml contained inside.

Is there anything of value that I could do or should this thread/issue simply be closed/deleted?

**Closed** 2021-01-03 11:35 UTC
