### ISSUE TITLE
[Bug] Crashed after or at initial setup

### ISSUE THREAD

**Issue by HerroBert** [machiav3lli/oandbackupx#268] opened 2021-01-03 11:15 UTC
**Description**
App crashed after or at initial setup

**Steps To Reproduce**

1. open app
2. start initial settings
3. crashed at setting battery settings 

**Expected behavior**
Reach main menu

**Screenshots**
no...

**System Information(please complete the following information):**

- Device: Galaxy S9
- Android Version: 10
- ROM:  LOS 17.1
- App's Version: 4.
- other: Magisk

**Comment by machiav3lli** [comment] 2021-01-03 19:05
Any logs?

**Comment by HerroBert** [comment] 2021-01-03 20:48
I saw, that there is a problem with backup target sdcard with ext4. Somehow write permission was missing, but OandBackup should be running with root?

**Comment by machiav3lli** [comment] 2021-01-03 21:30
Could you please test the just-releases 5.0.0 and report back, thanks.

**Comment by HerroBert** [comment] 2021-01-03 23:39
to make that clear, I meant ext4-write-permission.

**Comment by tsiflimagas** [comment] 2021-01-03 23:56
@HerroBert are you actually able to use an ext4 formatted sdcard at all? I don't think you can on android.

**Comment by machiav3lli** [comment] 2021-01-04 18:26
OABX uses mix of SAF and root commands to move files. Nothing is used to handle a special FS.

**Comment by HerroBert** [comment] 2021-01-04 20:21
Ext4 is not a special filesystem. Seems to be that these "root-commands" are not working, should override all FS-permissions.

**Comment by machiav3lli** [comment] 2021-01-05 01:22
Under Android it's. System and data partitions are allowed to be ext4 (and mostly are) but external storage uses sdcardfs explicitly (a filesystem framework based on exFAT). OTG can be read and some apps can write over it, but it's not useable through SAF.

**Comment by machiav3lli** [comment] 2021-04-21 20:02
After a lengthy discussions in the TG/Matrix group, it seems that the system can't handle ext4 formatted external cards, as those for some reason have messed up permissions.

**Comment by machiav3lli** [comment] 2021-04-21 20:04
Other than that, the crash could be a duplicate of #284

**Closed** 2021-06-30 22:33 UTC
