### ISSUE TITLE
[Bug] Backup Timer broken, job did not run at schedule backup time

### ISSUE THREAD

**Issue by ioogithub** [machiav3lli/oandbackupx#199] opened 2020-11-05 06:27 UTC
## Description
A backup job was schedule for Midnight, when midnight came, nothing happened. The app did not back up the app

## Steps To Reproduce
1. Open oandbackupx
2. Tap red alarm click button
3. Set Interval in days: 1
4. Set Hour of the day: 0
5.  Tap "Custom list"
6. Tap "Update custom list"
7. Tap any app from the list, tap ok
8. Tap "Enable"
9. Wait until Midnight
10. Nothing happens, the job doesn't run, no backup is generated.
11. "The Time until next backup:" value was changed to "-1:-14"

## Expected behavior
The app should start to backup the items on the list.

## System Information(please complete the following information):
    Device: Moto G7Plus
    Android Version: 10
    ROM: LineageOS 17
    App's Version: 3.2.0

**Comment by ioogithub** [comment] 2020-11-06 05:35
I tested this again with the new version 4.0.0 of the app.

I created a new schedule job and it never ran, nothing happened at the schedule time.

Is this function supposed to be working? Has anyone else successfully set a scheduled job and it worked?

**Comment by ioogithub** [comment] 2020-11-09 05:19
This issue is related to: https://github.com/machiav3lli/oandbackupx/issues/201

What is happening is the app is actually trying to run at the schedule backup time however because it can't remember the backup location, it doesn't back anything up. The app runs and just stalls in the background. As soon as I open it, it asks me to select the location then it crashes.

**Comment by machiav3lli** [comment] 2021-01-03 21:45
Even on 5.0.0 there's some systems that are still killing the planned jobs, more investigation into this is needed.

**Comment by iexos** [comment] 2021-01-11 08:53
Scheduling didn't work for me either, last night was the first time it worked. I cannot say for sure what it was, nor if it keeps working now. I did these things:

1. Turn off vanilla oandbackup schedule (I had the suspicion it might be responsible, even though it was set to a different time)
2. Re-enable oabx schedule
3. Reboot

Device: FairPhone 3
OS: LineageOS 16.0

**Comment by gasull** [comment] 2021-01-14 02:57
I'm having the same problem.  This is the reason I continue using the old oandbackup.

ASUS_X00TD
LineageOS 16.0

**Comment by heinhuiz** [comment] 2021-01-31 00:22
I'm having this problem too, that's why I did this today:

I have a scheduled backup configured to run every 7 days at 01:00 that has never run as scheduled.
It should run today, and hoping it would start when I 'activate' the app myself, I opened it at 00:59. The setting of the scheduled backup stated: Time left: 00:01.
At 01:00 it did not start. Settings stated: Time left: 00:00.
At 01:01 it still did not start, and now the settings stated: Time left: 00:01. Note the absence of a minus sign, it states that it will start in 1 minute, not that it should have started 1 minute before. 
Same at 01:02 (Time left: 00:02) and 01:03 (Time left: 00:03) and that is when I started the backup myself. At completion, it correctly stated Time left: 6 days, 23:48.

Maybe this helps you solving the problem.

**Comment by machiav3lli** [comment] 2021-01-31 21:32
The reason of the problem is well known: Android system ignoring pre scheduled actions, even when the uses the JobScheduler class. I'll have to re-implement using other APIs and hopefully find one that work.
P.S. in the 5.0.0 test versions I tried other ways of scheduling e.g. WorkManager and those had the same problem.

**Comment by heinhuiz** [comment] 2021-02-05 09:43
Still, I do have other apps with scheduled tasks that always run without problems. FolderSync for instance, and of course Automate.

Speaking of Automate, would it be possible to perform the task there, or in Tasker? What event could be used?

**Comment by machiav3lli** [comment] 2021-02-05 21:25
@heinhuiz about the second one: it's already on my long todo-list with low priority. So has to wait.
About the first: There's classical way to plan actions and there's androidx APIs. I've been using the earlier before and wanted to move to the second as it's easier to maintain and better for battery. But seems google is presenting us with a half solution for now. It's on my short list and will be fixed in coming versions, when there's time for it.

**Closed** 2021-05-04 23:08 UTC
Labels: bug
