### ISSUE TITLE
please help i can't backup to microsd

### ISSUE THREAD

**Issue by qw123wh** [machiav3lli/oandbackupx#79] opened 2020-07-28 14:22 UTC
I can't backup apps and data to the microsd. Can you help me with instructions please. When I install a rom I usually also do wipe internal storage. And therefore save everything on the microsd.

**Comment by Tiefkuehlpizze** [comment] 2020-07-29 09:21
Hi, Access to external storage is limited by Android's Framework. The Dialog returns a URI that maps a resource which is understood and mapped by the Storage Access Framework.
There is currently no way of doing backups to any other storage than the device internal storage. This is likely a duplicate of #32 and I've elaborated the problem in #76 

I cannot announce anything here, but I'm trying to find a solution for this problem on my own. But it will take a while.

**Comment by qw123wh** [comment] 2020-07-29 09:26
ok thanks yes it's a duplicate of 32 I hadn't noticed sorry.  However I hope you will be able to find a solution.  Thanks again

**Closed** 2020-07-30 17:36 UTC
