### ISSUE TITLE
[Bug] Schedule runs at a different time than configured

### ISSUE THREAD

**Issue by cyrildtm** [machiav3lli/oandbackupx#430] opened 2021-11-23 03:20 UTC
**Description**
I have a scheduled backup that runs at 2 am in the morning. It's right after 10 pm now in Eastern time, and the app says the time left before this backup is 3:49. 
However the backup just ran at 10 pm local time, which would be 2 am for UTC-1 ??
I have spotted a few unwanted backup in the past few days; I just started using this app. I'm still trying to figure out what happened. 

**Steps To Reproduce**

1. Set up a scheduled backup using my local time. 
2. Wait and use my phone normally. 
3. Scheduled backup runs at a different time. 

**Expected behavior**
Consistent time to run scheduled backup with the setup. 

**Screenshots**
I looked at logs, which was empty right after the backup finished. I don't know what to do about that. I will turn on Android's notification history for a while and see if I can find a pattern from more backup schedules being executed. 

**System Information(please complete the following information):**

- Device: Pixel 3xl
- Android Version: 11
- ROM: (AOSP, MIUI, OOS...)  LOS 18.1
- I turned off battery optimization for this app. Schedules should be able to run at correct times (I have alarms, calendar, etc.)
- App's Version: 7.0.0

**Comment by machiav3lli** [comment] 2021-11-25 07:47
This should be already fixed in the latest alpha (you can get it from the communiy groups).

**Closed by machiav3lli** 2021-11-25 07:47 UTC

**Comment by machiav3lli** [comment] 2021-11-25 07:50
And a duplicate of #370
