### ISSUE TITLE
Scheduled backup does not start as desired.

### ISSUE THREAD

**Issue by misterhsp** [machiav3lli/oandbackupx#370] opened 2021-06-18 02:46 UTC
Fixed at 2 o'clock at night, interval is set to 1 day. But nothing starts during the night. Every morning after getting up when I unlock the display starts the scheduled backup.

...

**Comment by machiav3lli** [comment] 2021-06-18 08:42
This is caused by how Android manages scheduled services. The OS decides when a scheduled service can start, this depends on if the system in doze is and if there's enough resources available.

I've already tested more strict scheduling in some earlier test versions, that resulted the action not launching at all sometimes. What we have now is a compromise I've talked about with the users in the community group. Should be in the future some more options available, I'll test those.

Till then, try to schedule a backup on a time, where your device isn't usually in a deep doze.

**Comment by misterhsp** [comment] 2021-06-18 13:06
Thanks for the explanation

Danke für die Erklärung :)

**Comment by machiav3lli** [comment] 2021-06-18 14:10
@misterhsp Aber gerne

**Comment by ivoanjo** [comment] 2021-06-20 10:15
Thanks for clarifying this, although the current behavior is rather inconvenient as sometimes apps get paused/stopped for backup while in active use...

**Comment by machiav3lli** [comment] 2021-06-20 14:14
@ivoanjo about this stop/cont behaviour, you can uncheck the option found in settings->advanced settings.

**Comment by misterhsp** [comment] 2021-06-23 15:34
Can one take there manually influence on it, that one brings the nevertheless in the night to run?

...

**Comment by GodKratos** [comment] 2021-08-03 21:04
My backups (scheduled every 3 days) had not run for over a month in OAndBackupX until I opened the app directly for a minute and then the scheduled jobs suddenly kicked off. I have it excluded from battery optimisations and everything.

Titanium Backup however, runs its backup on time every time without any problem and I never open the app so there must be a better way to do this.

**Comment by machiav3lli** [comment] 2021-11-25 07:52
This should be already fixed in the latest alpha (can be found in the community group).

**Closed** 2021-11-25 07:52 UTC

**Comment by misterhsp** [comment] 2021-11-25 13:33
Do you have a download link?

...

**Comment by machiav3lli** [comment] 2021-11-25 14:48
@misterhsp https://t.me/OAndBackupX/24858

**Comment by misterhsp** [comment] 2021-11-25 16:47
downloading the apk is somehow not possible.

...

**Comment by machiav3lli** [comment] 2021-11-30 08:41
@misterhsp try [this](https://mark.nl.tab.digital/s/5CAe9AoyWw6s9DJ)

**Comment by heinhuiz** [comment] 2021-12-04 08:38
> This should be already fixed in the latest alpha (can be found in the community group).

This alpha shows an alarm icon in the status bar when a schedule is set. For me, that is unacceptable. I need that icon for proper purposes, e.g. when real alarms are set.

You really need to rethink this and use a (hideable) persistent notification.

**Comment by machiav3lli** [comment] 2021-12-04 10:04
@heinhuiz it's using the alarm's API to make sure the schedule run, the only other option would be to have a running service which is too costy for the battery which is even less acceptable. This is a compromiss that didn't get any negative feedback from the people who had the issue (till this one), as it solves a reliability issue.

**Comment by heinhuiz** [comment] 2021-12-04 12:09
> @heinhuiz it's using the alarm's API to make sure the schedule run, the only other option would be to have a running service which is too costy for the battery which is even less acceptable. This is a compromiss that didn't get any negative feedback from the people who had the issue (till this one), as it solves a reliability issue.

I have directed you earlier to [FairEmail](https://github.com/M66B/FairEmail), which uses a background service (the one with the _Receive_ notification) of whit negligible battery consumption (< 1%). But it's your app, you make the decisions. Only if you keep it this way I will not use the app. 

If you insist to use the alarm API then I advice you to make the scheduling more user friendly, with day choices (every Monday/Tuesday etc./Weekday/Weekend) instead of the current every xx days. 

Good luck with your project.
