### ISSUE TITLE
[Feature Request] Display main app list fast and background process the detailed app scan

### ISSUE THREAD

**Issue by JohnCGH** [machiav3lli/oandbackupx#489] opened 2022-02-14 21:52 UTC
**Is your feature request related to a problem? Please describe it.**
When OABX is started, it takes a reletively long time (6-10 seconds) to scan all the apps of the device before the app list is displayed, and before I am able to start using the app.

**Describe the primary solution**
Titanium backup was able to display the list of apps within about 2 seconds. Then *after* the list was displayed for about 6 seconds, a toast message appeared saying "All application info has been loaded from the OS!"

So, it seems like TIB first does a quick package enumeration, then displays the app list quickly, but it also seems like it is processing the majority of the details for each app in a background process that completes a few seconds later.

Having the app list being displayed quickly allows me to start using the app right away and by the time I can open the details of the desired app, the background "details" for it will be ready by then.

It would be cool if OABX can also do this deferred-app-processing when launched.

**Comment by machiav3lli** [comment] 2022-02-15 02:19
Duplicate of #451

**Closed by machiav3lli** 2022-02-15 02:19 UTC
