### ISSUE TITLE
su needed to store. error 13

### ISSUE THREAD

**Issue by galenthurber** [machiav3lli/oandbackupx#76] opened 2020-07-26 22:49 UTC
Needs to be able to backup as user to SD, not su

**Comment by Atrate** [comment] 2020-07-26 23:29
Could you elaborate?

**Comment by Tiefkuehlpizze** [comment] 2020-07-27 07:21
Might be a duplicate of #32.
I've tried some things recently and from my observation, there are two options:
First is to implement an own "root" filebrowser to select the external storage path `/mnt/media_rw/ABCD-1234` and do _everything_ as root. And this means everything, because the app itself does not have access to the external storage path.
To solve this problem, you would need the second solution and use Storage Access Framework.
It's not a file system per se, it's something abstract that knows files and directories. I think, with a lot of work, it's possible to refactor the app to use it. And as bonus, users would be able to select their cloud storage or whatever authority Android offers.

**Comment by machiav3lli** [comment] 2020-07-30 17:52
@Tiefkuehlpizze this is my Idea refactoring the backup logic to be compatible with (Document)File and further overlaps with SAF

**Comment by Tiefkuehlpizze** [comment] 2020-07-30 21:25
@machiav3lli Are you working on something already? I'm doing some experiments with DocumentFile. But it'll probably need a lot more time and touches again some core structures as far as I can estimate.
I'm currently a bit crippled, because my Android Emulator doesn't want to be rooted and having Play Store installed at the same time :/

**Comment by machiav3lli** [comment] 2020-07-30 22:15
I have an Idea how to solve the problem allowing for an implementation of SAF support, but that's something we can talk out if you've already been working on something in this direction. Write me on TG your ideas. As promised I'll be documenting the already done work and the TODOs in a Contribution file, so everything could be more dynamic and transparent.

**Closed** 2020-10-25 18:06 UTC
